### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by lkevinzc** [wzhouad/WPO#2]
Hi authors, thanks for the nice work. We are very interested in following your work to conduct our research.

<img width="418" alt="image" src="https://github.com/user-attachments/assets/d6adba1a-5aae-4bf9-bcb7-8012dad26cf0">

In the paper, it says that the data is collected by GPT4 and Llama-2. I am just curious what is the ratio of GPT4 and Llama-2 outputs? And also whether you have used GPT4's output to train the models that you test on Alpaca Eval 2.0? Many thanks!

**Comment by wzhouad** [comment]
In the off-policy setting, we utilize the [Ultrafeedback dataset ](https://huggingface.co/datasets/HuggingFaceH4/ultrafeedback_binarized).  The sections on GPT-4 and Llama-2 detail their method for generating the data, which we have adopted for our use. For details on the model ratios, you can refer to their paper. We used GPT-4's output to train the models in both the off-policy setting (where Ultrafeedback uses GPT-4) and the hybrid setting.
